services:
  demo:
    build: ./demo
    container_name: demo
    depends_on:
    - exchange
    environment:
    - RABBITMQ_DEFAULT_USER=myuser
    - RABBITMQ_DEFAULT_PASS=mypassword
    - MODULE_NAME=demo
    - MODULE_INDEX=1
    - DUNI_ID=0XF5B33A71C991
  exchange:
    build: ./exchange
    container_name: exchange
    environment:
    - RABBITMQ_DEFAULT_USER=myuser
    - RABBITMQ_DEFAULT_PASS=mypassword
    - MODULE_NAME=exchange
    - MODULE_INDEX=1
    - DUNI_ID=0XF5B33A71C991
    image: rabbitmq-management
    ports:
    - 8081:15672
    - 5672:5672
version: '3.9'
